---
title: "Investments: Chapter 1"
date: "12/28/2015"
output: html_document
runtime: shiny
---

# Real vs Financial Assets

Real assets are the property, plants, and equipment which constitute the productive capabilities of our economy.  Financial assets are merely claims on these assets.  In fact, the sum of all financial assets in the economy is zero.  This is because, for example, a bond is a liability to the issuing company, and an asset to the holder.

## The purpose of financial assets

While financial assets are claims on real assets, and would not exist in an of themselves, this doesn't mean financial assets do not affect real assets.  In fact, the existence of financial assets fosters the creation of many more real assets.  Further, the better financial markets function, the more real assets can be created.

There are a couple reasons for this.  First, many investors can easily pool money to buy (or build) real assets.  Second, financial assets make it much easier to transfer ownership of real assets.   Investors are more likely to invest if they may easily exit the investment without significant loss in the investment's value (there is less 'liquidity risk').

# What Do Markets Do?  

What is often overlooked in finance and economics education is a coherent explanation of why we have markets.  In fact, often graduates of these programs cannot say for certain what markets do---in my experience they often will say something about markets allowing competition.  This answer is unsatisfactory because competition in markets is a means to achieve the markets actual purpose, not the purpose itself.  Moreover, 'free' markets will often tend toward monopoly an no competition.  We have to put many constraints on markets (make them less 'free') in order to enable competition.  

Put simply, markets serve two important purposes:

#.  Aggregate Information
#.  Organize Society

We can show this by asking the question: why were there bread lines in the Soviet Union?  That is to say, why when prices are fixed do you often get the situation where the economy runs out of some good? To answer this question consider the following chain of events.

#. There is a fungus which destroys much of the Soviet wheat crop.
#. The price of wheat and bread are fixed, so
	- consumer demand for bread is unchanged
	- there is no incentive for other farmers to switch from their crop (say corn) to wheat
#. Given reduced wheat supply, and unchanged demand, eventually wheat stocks are exhausted.

Now consider this same scenario when we use a market and prices are allowed to adjust.

#. There is a fungus which destroys much of the US wheat crop.
#.  

The last point I will make here is to note that US policy is often to fix prices, or suppress a market's ability to function. Take the US mortgage market as an example.  Instead of allowing mortgage interest rates to be market determined, thereby aggregating information and organizing society, the US has set a policy of keeping these rates artificially low to encourage homeownership. This mortgage markets aggregate incorrect information, and organize society in such a way as to have us spend more on housing than we otherwise would.


<!-- Move the below into a new chapter 2 -->

# Trading Securities



## Trades, Orders, and the Limit Order Book

```{r orderbook, echo = FALSE}
## app to allow students enter order and see the effect on the limit orderbook
library(orderbook)
## make panel input conditinal
## i'll also need a submit button
inputPanel(

    )

renderPrint({
filename <- system.file("extdata",
 "sample.txt", package = "orderbook")
 ob <- orderbook(file = filename)
 ob <- read.orders(ob, 10000)
display(ob)
add.order(ob, 11.37, 300, "ASK")
    })



```


## Next Section
